name: CI

on: push

env:
    SVC_NAME: sk-codename-svc

jobs:
  gitHubActionForPylint:
    name: GitHub Action for pylint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v5
        with:
            python-version: 3.11
      - run: pip install pipenv pylint flake8
    #   - run: pipenv sync && pipenv run pylint **/*.py
      - run: docker build -t ${{ env.SVC_NAME }} .
