name: CI

on: push

jobs:
  gitHubActionForPylint:
    name: GitHub Action for pylint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v5
        with:
            python-version: 3.11
      - run: pip install pipenv
      - run: pipenv sync
      - run: pylint **/*.py
